#pragma once

typedef enum
{
	SCREEN_MAIN_DRAW = 0,
	SCREEN_MAIN_REFRESH = 1,
	SCREEN_MAIN_IDLE = 2,
	
	SCREEN_CONF_MENU_DRAW = 10,
	SCREEN_CONF_MENU_IDLE = 11,

	SCREEN_FAST_RESET_DRAW = 14,
	SCREEN_FAST_RESET_IDLE = 15,

	SCREEN_CONF_OUTPUT_SETUP = 100,
	SCREEN_CONF_OUTPUT_DRAW  = 101,
	SCREEN_CONF_OUTPUT_IDLE  = 102,


	SCREEN_CONF_LOCOLIST_SETUP = 105,
	SCREEN_CONF_LOCOLIST_DRAW  = 106,
	SCREEN_CONF_LOCOLIST_IDLE  = 107,

	SCREEN_CONF_LOCOSLOT1_SETUP = 110,
	SCREEN_CONF_LOCOSLOT1_DRAW  = 111,
	SCREEN_CONF_LOCOSLOT1_IDLE  = 112,

	SCREEN_CONF_LOCOSLOT2A_SETUP = 103,
	SCREEN_CONF_LOCOSLOT2A_DRAW  = 104,
	SCREEN_CONF_LOCOSLOT2A_IDLE  = 108,

	SCREEN_CONF_LOCOSLOT2B_SETUP = 113,
	SCREEN_CONF_LOCOSLOT2B_DRAW  = 114,
	SCREEN_CONF_LOCOSLOT2B_IDLE  = 115,

	SCREEN_CONF_LOCOSLOT3_SETUP = 116,
	SCREEN_CONF_LOCOSLOT3_DRAW  = 117,
	SCREEN_CONF_LOCOSLOT3_IDLE  = 118,

	SCREEN_LOAD_CONF_SETUP = 120,
	SCREEN_LOAD_CONF_DRAW = 121,
	SCREEN_LOAD_CONF_IDLE = 122,

	SCREEN_CONF_DELAY_SETUP = 125,
	SCREEN_CONF_DELAY_DRAW = 126,
	SCREEN_CONF_DELAY_IDLE = 127,

	SCREEN_CONF_PAUSED_SETUP = 130,
	SCREEN_CONF_PAUSED_DRAW = 131,
	SCREEN_CONF_PAUSED_IDLE = 132,
	
	SCREEN_CONF_MIDDELAY_SETUP = 135,
	SCREEN_CONF_MIDDELAY_DRAW = 136,
	SCREEN_CONF_MIDDELAY_IDLE = 137,
	
	SCREEN_CONF_INTSENSE_SETUP = 140,
	SCREEN_CONF_INTSENSE_DRAW  = 141,
	SCREEN_CONF_INTSENSE_IDLE  = 142,

	SCREEN_CONF_ACCLIST_SETUP = 145,
	SCREEN_CONF_ACCLIST_DRAW  = 146,
	SCREEN_CONF_ACCLIST_IDLE  = 147,

	SCREEN_CONF_ACCCONF_SETUP  = 150,
	SCREEN_CONF_ACCCONF_DRAW   = 151,
	SCREEN_CONF_ACCCONF_IDLE   = 152,
	
	SCREEN_CONF_RELEARN_SETUP = 153,
	SCREEN_CONF_RELEARN_DRAW = 154,
	SCREEN_CONF_RELEARN_IDLE = 155,

	SCREEN_CONF_STARTDIR_SETUP = 157,
	SCREEN_CONF_STARTDIR_DRAW = 158,
	SCREEN_CONF_STARTDIR_IDLE = 159,

	SCREEN_CONF_SAVESTATE_SETUP = 160,
	SCREEN_CONF_SAVESTATE_DRAW = 161,
	SCREEN_CONF_SAVESTATE_IDLE = 162,

	SCREEN_CONF_TRAVELDIR_SETUP = 164,
	SCREEN_CONF_TRAVELDIR_DRAW = 165,
	SCREEN_CONF_TRAVELDIR_IDLE = 166,

	SCREEN_CONF_BACKLITE_SETUP = 235,
	SCREEN_CONF_BACKLITE_DRAW  = 236,
	SCREEN_CONF_BACKLITE_IDLE  = 237,
	SCREEN_CONF_BACKLITE_OFF   = 238,

	SCREEN_CONF_MANUAL_SETUP = 240,
	SCREEN_CONF_MANUAL_DRAW  = 241,
	SCREEN_CONF_MANUAL_IDLE  = 242,

	SCREEN_CONF_RESET_SETUP = 245,
	SCREEN_CONF_RESET_DRAW  = 246,
	SCREEN_CONF_RESET_IDLE  = 247,

	SCREEN_CONF_DIAG_SETUP = 250,
	SCREEN_CONF_DIAG_DRAW  = 251,
	SCREEN_CONF_DIAG_IDLE  = 252,
	
	SCREEN_DONT_KNOW = 255

} ScreenState;


typedef struct
{
	const char* configName;
	ScreenState configScreen;
} ConfigurationOption;

const ConfigurationOption configurationOptions[] = 
{
  { "Locomotive Config",  SCREEN_CONF_LOCOLIST_SETUP },
  { "Accessory Config",   SCREEN_CONF_ACCLIST_SETUP },
  { "DC/DCC Output ",     SCREEN_CONF_OUTPUT_SETUP },
  { "Endpoint Delay",     SCREEN_CONF_DELAY_SETUP },
  { "Midpoint Delay",     SCREEN_CONF_MIDDELAY_SETUP },  
  { "Midpoints Enable",   SCREEN_CONF_INTSENSE_SETUP },
  { "Travel Mode",        SCREEN_CONF_TRAVELDIR_SETUP},
  { "Sensor Learning",    SCREEN_CONF_STARTDIR_SETUP },
  { "Stop Relearns Dir",  SCREEN_CONF_RELEARN_SETUP },
  { "Resume on Power On", SCREEN_CONF_SAVESTATE_SETUP },
  { "Pause on Start",     SCREEN_CONF_PAUSED_SETUP },
  { "Backlight Timeout",  SCREEN_CONF_BACKLITE_SETUP },  
  { "Turn Off Backlight", SCREEN_CONF_BACKLITE_OFF },  
  { "Diagnostics",        SCREEN_CONF_DIAG_SETUP },  
  { "Factory Reset",      SCREEN_CONF_RESET_SETUP },  
};

#define NUM_CONF_OPTIONS  (sizeof(configurationOptions)/sizeof(ConfigurationOption))

